###
POST http://localhost/api/auth/register
Accept: application/json
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"

Cazares
--WebAppBoundary
Content-Disposition: form-data; name="password"

{{password}}
--WebAppBoundary
Content-Disposition: form-data; name="phone"

319747474747
--WebAppBoundary
Content-Disposition: form-data; name="email"

{{email}}
--WebAppBoundary
Content-Disposition: form-data; name="type"

recruiter
--WebAppBoundary
Content-Disposition: form-data; name="profile_picture"; filename="profilePicture.png"

< profilePicture.jpeg
--WebAppBoundary--

###
POST http://localhost:80/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}
> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("bearerToken", response.body.access_token);
%}

###
GET http://localhost:80/api/auth/me
Accept: application/json
Authorization: Bearer {{bearerToken}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("profilePicture", response.body.data.profile_picture);
    client.global.set("userId", response.body.data.id);
%}
###

###
GET /{{profilePicture}}


###
GET http://localhost:80/api/user/{{userId}}
    ?includes[]=academicRecords
    &includes[]=competences
    &includes[]=professionalExperiences
accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
POST http://localhost:80/api/user/profile-picture/update
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="profile_picture"; filename="profilePicture.png"

< profilePicture.jpeg
--WebAppBoundary--



###
