POST http://localhost:80/api/auth/register
Accept: application/json
Content-Type: application/json

{
    "name": "test",
    "password": "testaa",
    "email": "davi.teste@gmail.com",
    "phone": "319747474747",
  "type": "recruiter"
}

###
POST http://localhost:80/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "name": "test",
  "password": "testaa",
  "email": "davi.teste@gmail.com",
  "phone": "319747474747",
  "type": "recruiter"
}

###

GET http://localhost:80/api/auth/me
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNzE0MzM1NjI3LCJleHAiOjE3MTQzMzkyMjcsIm5iZiI6MTcxNDMzNTYyNywianRpIjoiZDhZR05jRHNLUXB5eGt6NCIsInN1YiI6IjcyIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.kwYnbaH6ICB1IhHnWDY6AooBowMLpsxp8SMtUfgT_6k
